# Generated by Django 3.0.6 on 2020-05-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_actualite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courriels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Courriels',
            },
        ),
    ]
