# Generated by Django 3.0.6 on 2020-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_courriels'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rapports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Rapports',
            },
        ),
    ]
